#!/usr/bin/env bash

set -ex
set -o pipefail

docker run -it \
        -p 51235:51235 \
        --mount type=volume,source=rippled,target=/rippled \
        seelabs/rippled_dev:0.1 \
        /bin/bash

